POST http://localhost:8080/console/execute/result
Content-Type: text/groovy
Accept: text/plain
X-Console-Verify: 5d4d0252-503c-4fe2-9bba-8a8bcab3dbd7

// language=groovy
emailDigestJobProduceEmailsForDigest()